[phases.install]
cmds = ["...", "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader"]


[phases.build]
cmds = ["echo build started", "npm run build", "php artisan migrate --force", "php artisan optimize", "echo build ended"]
